# Generated by Django 5.1.5 on 2025-05-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
